package:
  name:pythontemplate
  version: "0.0.0"

source:
# this is used for build from git hub
  git_rev: 0.0.0
  git_url: https://github.com/{{github_login}}/pythontemplate.git

# this is used for pypi
  # fn: io3d-1.0.30.tar.gz
  # url: https://pypi.python.org/packages/source/i/io3d/io3d-1.0.30.tar.gz
  # md5: a3ce512c4c97ac2410e6dcc96a801bd8
#  patches:
   # List any patch files here
   # - fix.patch
build:
  ignore_prefix_files:
    - devel
    - examples
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pythontemplate = pythontemplate:main
    #
    # Would create an entry point called io3d that calls pythontemplate.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  # spaces between package name and the fallowing symbols are not allowed
  build:
    - python=>3.6
    - setuptools

  run:
    - python>=3.6

## With square brackets in comment, the package required on windows can be specified
#    - pywin32 # [win]

## Set minimal version of requred package to major.minor in the time of package build
#    - {{ pin_compatible('io3d', max_pin='x.x') }}

test:
  # Python imports
  imports:
    - scaffan

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/{{github_login}}/pythontemplate
  license: MIT License
  summary: ''

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
